#! /bin/sh
#Constants
SCRIPTNAME="TDS18 Manager"

#Before Script

#Functions

#Script
case "$1" in
  compile)
	echo "Compiling"
	flex -o ./bin/lex.yy.c ./src/calc-lexico.l 
	bison -d -o ./bin/calc-sintaxis.tab.c ./src/calc-sintaxis.y
	gcc ./bin/lex.yy.c ./bin/calc-sintaxis.tab.c -o ./bin/main
	;;
  compile_flags)
	echo "Compiling"
	flex -o ./bin/lex.yy.c ./src/calc-lexico.l 
	bison -v -o ./bin/calc-sintaxis.tab.c ./src/calc-sintaxis.y 
	gcc ./bin/lex.yy.c ./bin/calc-sintaxis.tab.c -o ./bin/main
	;;
  run)
	./bin/main $2
	;;
  test)
	echo "Testing"
	for filename in ./test/*.txt; do
		echo "------  Test  $filename ------"
		./bin/main $filename
		echo "------ END TEST ------\n"
	done
	;;
  quickrun)
	echo "Compiling"
	flex -o ./bin/lex.yy.c ./src/calc-lexico.l 
	bison -d -o ./bin/calc-sintaxis.tab.c ./src/calc-sintaxis.y
	gcc ./bin/lex.yy.c ./bin/calc-sintaxis.tab.c -o ./bin/main
	echo "Running"
	./bin/main $2
	;;
  clean)
	rm bin/*
	;;
  *)
	echo "Usage: $SCRIPTNAME {compile|run|test|quickrun|clean}" >&2
	exit 3
	;;
esac

exit 0
