#! /bin/sh
#Constants
SCRIPTNAME="TDS18 Manager"
BUILD="./src"
OUTPUT="./bin"

#Before Script

#Functions

#Script
case "$1" in
  compile)
	echo "Compiling"
	flex -o $OUTPUT/lex.yy.c $BUILD/calc-lexico.l 
	bison -d -o $OUTPUT/calc-sintaxis.tab.c $BUILD/calc-sintaxis.y
	gcc -I $BUILD $BUILD/*.c $OUTPUT/lex.yy.c $OUTPUT/calc-sintaxis.tab.c -o $OUTPUT/main
	;;
  compile_flags)
	echo "Compiling"
	flex -o $OUTPUT/lex.yy.c $BUILD/calc-lexico.l 
	bison -v -o $OUTPUT/calc-sintaxis.tab.c $BUILD/calc-sintaxis.y 
	gcc -I $BUILD $BUILD/*.c $OUTPUT/lex.yy.c $OUTPUT/calc-sintaxis.tab.c -o $BUILD/main
	;;
  run)
	$OUTPUT/main $2
	;;
  test)
	echo "Testing"
	for filename in ./test/*.txt; do
		echo "------  Test  $filename ------"
		$OUTPUT/main $filename
		echo "------ END TEST ------\n"
	done
	;;
  quickrun)
	echo "Compiling"
	flex -o $OUTPUT/lex.yy.c $BUILD/calc-lexico.l 
	bison -d -o $OUTPUT/calc-sintaxis.tab.c $BUILD/calc-sintaxis.y
	gcc -I $BUILD $BUILD/*.c $OUTPUT/lex.yy.c $OUTPUT/calc-sintaxis.tab.c -o $OUTPUT/main
	echo "Running"
	$OUTPUT/main $2
	;;
  clean)
	rm $OUTPUT
	;;
  *)
	echo "Usage: $SCRIPTNAME {compile|run|test|quickrun|clean}" >&2
	exit 3
	;;
esac

exit 0
